[RAC] Mutiple fixes and update AC types
* Now the parse has a version depending on the commit hash.
* Update AC headers to 4.6.4.
* Add array/tuple definitions for tools which does not support C++11.

* Fix a segfaut in statements.cpp.
* Disable the load of acl2-customization.lsp during certification (in
  some cases, it can make the certification fails).
* .gitignore: new.
* Fix some tests.

diff --git a/books/projects/rac/src/rac-skel b/books/projects/rac/src/rac-skel
--- a/books/projects/rac/src/rac-skel
+++ b/books/projects/rac/src/rac-skel
@@ -121,7 +121,9 @@ then
 
     $parseBin $basename -acl2 $basename.ast.lsp
 
-    $acl2Bin > $basename.acl2.log <<EOF
+    # Disable the loading of acl2-customization.lsp which could break the
+    # certification.
+    ACL2_CUSTOMIZATION="NONE" $acl2Bin > $basename.acl2.log <<EOF
       (include-book "$translateBook")
       (set-inhibit-output-lst '(prove event proof-tree))
       (translate-program "$basename.ast.lsp" "$basename.lisp" state)
@@ -131,11 +133,16 @@ then
       (certify-book "$basename" 1)
 EOF
 
+# Deativate locally -e since, in the "happy" path, we want grep to fail.
+set +e
 cat $basename.acl2.log | grep 'ACL2 Error' &> /dev/null
+
 if [[ $? == "0" ]]
 then
   echo "Certification failed ! Please check $basename.acl2.log for more details."
   exit 1
-fi 
+fi
+
+set -e
 
 fi
